name: Netlify Deploy Editorial
on:
  push:
    branches:
      - 'editorial'
    paths: 
      - 'content/**'
      - 'data/**'
      - 'static/images/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DEPLOY_EDITORIAL }}
