name: Netlify Deploy
on:
  push:
    branches:
      - 'content_cms'
	paths:
		- 'content/**'
  		- 'data/**'
        - 'static/images/**'
  
jobs:
	merge:
    	runs-on: ubuntu-latest

    steps:
      - name: Checkout production
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Merge content_cms into production
        run: |
          git merge content_cms --no-ff --no-commit
          git commit -m "Merge content_cms into production"
          git push origin production
